stages:
  - publish

# Use local Sonarscanner to analyse the Code

publish:
  stage: publish
  only:
    - release
  script:
    - yarn install
    - yarn build
    - yarn doc
    - yarn test
    - sonar-scanner -Dsonar.inclusions=src/**/* -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
    - npm publish
