stages:
  - publish
  - test

# Use local Sonarscanner to analyse the Code

publish:
  stage: publish
  only:
    - release
  script:
    - npm install
    - npm run build
    - npm run doc
    - npm run test
    - sonar-scanner -Dsonar.projectKey=molly -Dsonar.inclusions=src/**/* -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
    - npm publish

test:
  stage: test
  only:
    - 1.4.0
  script:
    - npm install
    - npm run build
    - npm run test
    - sonar-scanner -Dsonar.projectKey=molly-dev -Dsonar.inclusions=src/**/* -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info