language: node_js
node_js:
- '9'
- '10'
- '11'
- '12'
notifications:
  email: markusgilg@outlook.de
env:
  global:
    - MONGO_VERSION=4.0.0
# make mongodb a replica set
before_script:
- mkdir -p downloads
- mkdir -p var/db var/log
- if [[ ! -d downloads/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION} ]] ; then cd downloads && wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}.tgz && tar xzf mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}.tgz && cd ..; fi
- downloads/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}/bin/mongod --version
- downloads/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}/bin/mongod --dbpath var/db --replSet rs0 --fork --logpath var/log/mongod.log
- sleep 10
- |-
  downloads/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}/bin/mongo --eval "rs.initiate({_id: 'rs0', members:[{_id: 0, host: '127.0.0.1:27017'}]});"
  sleep 15
jobs:
  include:
  - stage: build
    script: npm run build
  - stage: test
    script: npm run coverage
deploy:
  provider: npm
  email: markusgilg@outlook.de
  skip_cleanup: true
  api_key:
    secure: 8ac04a15-f5ea-467d-9376-5c63238b58fd
  on:
    branch: master
    repo: nodejayes/molly
