swagger: "2.0"
info:
  description: ""
  version: "1.3.2"
  title: "molly"
  contact:
    email: "markusgilg@outlook.de"
  license:
    name: "MIT"
host: "http://localhost:8086"
basePath: "/"
tags:
- name: "Right"
  description: ""
- name: "Group"
  description: ""
- name: "User"
  description: ""
schemes:
- "http"
paths:
  /create/Right:
    post:
      tags:
      - "Right"
      summary: ""
      description: ""
      operationId: "/create/Right"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
  type: "object"
  properties: 
    key: 
      type: "string"
    active: 
      type: "boolean"
  additionalProperties: false
  patterns: []

  /delete/Right:
    post:
      tags:
      - "Right"
      summary: ""
      description: ""
      operationId: "/delete/Right"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    id: 
      type: "string"
      minLength: 24
      maxLength: 24
  additionalProperties: false
  patterns: []
  required: 
    - "id"

  /read/Right:
    post:
      tags:
      - "Right"
      summary: ""
      description: ""
      operationId: "/read/Right"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    _id: 
      type: "string"
      minLength: 24
      maxLength: 24
    key: 
      type: "string"
    active: 
      type: "boolean"
  additionalProperties: false
  patterns: []

  /create/Group:
    post:
      tags:
      - "Group"
      summary: ""
      description: ""
      operationId: "/create/Group"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    name: 
      type: "string"
    rights: 
      type: "array"
      items: 
        enum: 
          - null
        type: "string"
        minLength: 24
        maxLength: 24
  additionalProperties: false
  patterns: []

  /update/Group:
    post:
      tags:
      - "Group"
      summary: ""
      description: ""
      operationId: "/update/Group"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    id: 
      type: "string"
      minLength: 24
      maxLength: 24
    updateSet: 
      type: "object"
      properties: 
        name: 
          type: "string"
        rights: 
          type: "array"
          items: 
            type: "string"
            minLength: 24
            maxLength: 24
      additionalProperties: false
      patterns: []
  additionalProperties: false
  patterns: []
  required: 
    - "id"

  /delete/Group:
    post:
      tags:
      - "Group"
      summary: ""
      description: ""
      operationId: "/delete/Group"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    id: 
      type: "string"
      minLength: 24
      maxLength: 24
  additionalProperties: false
  patterns: []
  required: 
    - "id"

  /read/Group:
    post:
      tags:
      - "Group"
      summary: ""
      description: ""
      operationId: "/read/Group"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    _id: 
      type: "string"
      minLength: 24
      maxLength: 24
    name: 
      type: "string"
    rights: 
      type: "array"
      items: 
        type: "object"
        properties: 
          _id: 
            type: "string"
            minLength: 24
            maxLength: 24
          key: 
            type: "string"
          active: 
            type: "boolean"
        additionalProperties: false
        patterns: []
  additionalProperties: false
  patterns: []

  /create/User:
    post:
      tags:
      - "User"
      summary: ""
      description: ""
      operationId: "/create/User"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    username: 
      type: "string"
      minLength: 3
    password: 
      type: "string"
    email: 
      type: "string"
      format: "email"
    group: 
      enum: 
        - null
      type: "string"
      minLength: 24
      maxLength: 24
  additionalProperties: false
  patterns: []

  /update/User:
    post:
      tags:
      - "User"
      summary: ""
      description: ""
      operationId: "/update/User"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    id: 
      type: "string"
      minLength: 24
      maxLength: 24
    updateSet: 
      type: "object"
      properties: 
        username: 
          type: "string"
          minLength: 3
        password: 
          type: "string"
        email: 
          type: "string"
          format: "email"
        group: 
          type: "string"
          minLength: 24
          maxLength: 24
      additionalProperties: false
      patterns: []
  additionalProperties: false
  patterns: []
  required: 
    - "id"

  /delete/User:
    post:
      tags:
      - "User"
      summary: ""
      description: ""
      operationId: "/delete/User"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    id: 
      type: "string"
      minLength: 24
      maxLength: 24
  additionalProperties: false
  patterns: []
  required: 
    - "id"

  /read/User:
    post:
      tags:
      - "User"
      summary: ""
      description: ""
      operationId: "/read/User"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: 'object'
          properties:
          params:
            type: 'object'
            properties:
            key:
              type: 'string'
            RESTRICTIONS:
              type: 'object'
              limit: 'number'
      responses:
        200:
          description: ""
          schema:
          ---
  type: "object"
  properties: 
    _id: 
      type: "string"
      minLength: 24
      maxLength: 24
    username: 
      type: "string"
      minLength: 3
    password: 
      type: "string"
    email: 
      type: "string"
      format: "email"
    group: 
      type: "object"
      properties: 
        _id: 
          type: "string"
          minLength: 24
          maxLength: 24
        name: 
          type: "string"
        rights: 
          type: "array"
          items: 
            type: "object"
            properties: 
              _id: 
                type: "string"
                minLength: 24
                maxLength: 24
              key: 
                type: "string"
              active: 
                type: "boolean"
            additionalProperties: false
            patterns: []
      additionalProperties: false
      patterns: []
  additionalProperties: false
  patterns: []
